version: "3.8"

services:
  led-display:
    container_name: led-display
    build: .
    restart: always
    privileged: true
    network_mode: "host"
    environment:
      - DISPLAY=:0
    volumes:
      - /srv/ledram:/srv/ledram  
    devices:
      - "/dev/fb0:/dev/fb0"
      - "/dev/mem:/dev/mem"
